### ISSUE TITLE
Not defined SQLite

### ISSUE THREAD

**Issue by saibaba0119** [Fabricio-191/docs#1]
const Database = require('simplest.db').SQLite;
const db = new SQLite({
	path: './database.sqlite',
});

when i am running this code i am getting error that SQLite is not defined. (const db = new SQLite())

Please help me how to reslove it

Thanks

**Comment by Fabricio-191** [comment]
![imagen](https://user-images.githubusercontent.com/47196132/205113663-cfa3a46e-19e3-4d96-b41a-0121a9979499.png)
```js
const Database= require('simplest.db').SQLite;
const db = new Database({
path: './database.sqlite',
});
```

First of all, that error is really basic you should have learn't that in a tutorial or something
Second, this is not the correct github repository
Third, the example was corrected in the docs, thanks for your help
