### ISSUE TITLE
Unable to create table and insert records

### ISSUE THREAD

**Issue by saibaba0119** [Fabricio-191/docs#2]
When i run the below code, sqlite file has created, but on with db instance, i am unable to create table and insert records into sqlite database.
![Screenshot 2022-12-01 230021](https://user-images.githubusercontent.com/73639903/205121656-5c3ddef2-3b0d-43c6-8712-0c834cfd5b6f.png)

Getting Error that, Cannot read properties of undefined (reading 'create')

Please help me with this. 

This module is suitable for my scenario.

**Comment by Fabricio-191** [comment]
Man, this module is unfinished, you shouldn't use it, and this is not the correct github repository

**Comment by Fabricio-191** [comment]
And actually, you are confusing SQLazo with simplest.db, the code you have there is from SQLazo but that is a private repository of mine, you cant use it, you have installed simplest.db

I will hide SQLazo docs to avoid this confusion
